# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0002_initial"),
        ("turnos", "0001_initial"),
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONFIRMACION", "Confirmación de Turno"),
                            ("RECORDATORIO_24H", "Recordatorio 24 horas"),
                            ("RECORDATORIO_2H", "Recordatorio 2 horas"),
                            ("CANCELACION", "Cancelación de Turno"),
                            ("MODIFICACION", "Modificación de Turno"),
                            ("SEGUIMIENTO", "Seguimiento Post-tratamiento"),
                            ("PROMOCION", "Promoción"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField()),
                ("telefono_destino", models.CharField(max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADO", "Enviado"),
                            ("ENTREGADO", "Entregado"),
                            ("LEIDO", "Leído"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("mensaje_id_externo", models.CharField(blank=True, max_length=100)),
                ("error_mensaje", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("enviado_en", models.DateTimeField(blank=True, null=True)),
                ("entregado_en", models.DateTimeField(blank=True, null=True)),
                ("leido_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones",
                        to="turnos.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "estado", "creado_en"],
                        name="notificacio_sucursa_0cd56d_idx",
                    ),
                    models.Index(
                        fields=["cliente", "creado_en"],
                        name="notificacio_cliente_a5da46_idx",
                    ),
                ],
            },
        ),
    ]
