# Generated by Django 4.2.7 on 2026-01-14 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0003_usuario_dias_laborales_usuario_horario_fin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notificaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONFIRMACION", "Confirmación de Turno"),
                            ("RECORDATORIO_24H", "Recordatorio 24 horas"),
                            ("RECORDATORIO_2H", "Recordatorio 2 horas"),
                            ("CANCELACION", "Cancelación de Turno"),
                            ("MODIFICACION", "Modificación de Turno"),
                            ("PROMOCION", "Mensaje Promocional"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido del mensaje. Usa variables: {nombre_cliente}, {fecha}, {hora}, {servicio}, {profesional}, {sucursal_nombre}, {sucursal_direccion}"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si está inactivo, se usa el mensaje por defecto",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_templates_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_templates",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Mensaje",
                "verbose_name_plural": "Plantillas de Mensajes",
                "ordering": ["tipo"],
                "unique_together": {("sucursal", "tipo")},
            },
        ),
    ]
