# Generated by Django 4.2.7 on 2026-08-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0003_usuario_dias_laborales_usuario_horario_fin_and_more"),
        # Apunta a 0007 y no a la última de clientes a propósito: clientes.0008
        # copia los tokens a esta tabla antes de borrar la columna, así que
        # depende de esta migración. Apuntar a 0008 cerraría el círculo.
        ("clientes", "0007_alter_vinculacioncliente_metodo_vinculacion"),
        ("notificaciones", "0003_crear_templates_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(help_text="Clave del evento", max_length=50),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TURNOS", "Turnos"),
                            ("RUTINA", "Mi rutina"),
                            ("NOVEDADES", "Novedades"),
                            ("PROMOCIONES", "Promociones"),
                        ],
                        help_text="Se copia del evento al crear, para poder filtrar sin resolver el catálogo.",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("cuerpo", models.CharField(max_length=400)),
                (
                    "datos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Carga útil que viaja al teléfono: ruta de la app e ids del origen.",
                    ),
                ),
                (
                    "clave",
                    models.CharField(
                        blank=True,
                        help_text="Clave de idempotencia. Nula para avisos que sí pueden repetirse.",
                        max_length=120,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "programado_para",
                    models.DateTimeField(
                        help_text="No sale antes de este momento. Igual a la creación si es inmediato."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESANDO", "En curso"),
                            ("ENVIADO", "Enviado"),
                            ("SIN_DESTINO", "Sin dispositivo activo"),
                            ("FALLIDO", "Fallido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("enviado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "centro_estetica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="empleados.centroestetica",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ficha del centro, para rastrear el aviso desde el CRM.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avisos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "usuario_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="clientes.usuariocliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="DispositivoPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Expo push token (ExponentPushToken[...])",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                            ("DESCONOCIDA", "Desconocida"),
                        ],
                        default="DESCONOCIDA",
                        max_length=15,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "motivo_baja",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SESION_CERRADA", "Cerró sesión"),
                            ("TOKEN_MUERTO", "Expo lo rechazó (app desinstalada)"),
                            ("REASIGNADO", "El teléfono pasó a otra cuenta"),
                        ],
                        help_text="Por qué se dio de baja. Vacío mientras está activo.",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositivos_push",
                        to="clientes.usuariocliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo push",
                "verbose_name_plural": "Dispositivos push",
                "ordering": ["-actualizado_en"],
            },
        ),
        migrations.CreateModel(
            name="PreferenciaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TURNOS", "Turnos"),
                            ("RUTINA", "Mi rutina"),
                            ("NOVEDADES", "Novedades"),
                            ("PROMOCIONES", "Promociones"),
                        ],
                        max_length=20,
                    ),
                ),
                ("habilitada", models.BooleanField(default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "usuario_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_notificacion",
                        to="clientes.usuariocliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de notificación",
                "verbose_name_plural": "Preferencias de notificación",
                "ordering": ["categoria"],
                "unique_together": {("usuario_cliente", "categoria")},
            },
        ),
        migrations.CreateModel(
            name="PlantillaNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        help_text="Clave del evento (ver apps.notificaciones.eventos)",
                        max_length=50,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título de la notificación. Admite variables entre llaves.",
                        max_length=100,
                    ),
                ),
                (
                    "cuerpo",
                    models.CharField(
                        help_text="Cuerpo de la notificación. Admite variables entre llaves.",
                        max_length=300,
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si se desactiva, vuelve a usarse el texto por defecto.",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "centro_estetica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_notificacion",
                        to="empleados.centroestetica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de notificación",
                "verbose_name_plural": "Plantillas de notificación",
                "ordering": ["evento"],
                "unique_together": {("centro_estetica", "evento")},
            },
        ),
        migrations.CreateModel(
            name="EnvioPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACEPTADO", "Aceptado por Expo"),
                            ("ENTREGADO", "Entregado"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        blank=True,
                        help_text="Id que devuelve Expo al aceptar el mensaje; se usa para pedir el recibo.",
                        max_length=64,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmado_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo se leyó el recibo definitivo de Expo.",
                        null=True,
                    ),
                ),
                (
                    "aviso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="notificaciones.aviso",
                    ),
                ),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="notificaciones.dispositivopush",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío push",
                "verbose_name_plural": "Envíos push",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["estado", "creado_en"],
                        name="notificacio_estado_957326_idx",
                    )
                ],
                "unique_together": {("aviso", "dispositivo")},
            },
        ),
        migrations.AddIndex(
            model_name="dispositivopush",
            index=models.Index(
                fields=["usuario_cliente", "activo"],
                name="notificacio_usuario_8ec907_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aviso",
            index=models.Index(
                fields=["estado", "programado_para"],
                name="notificacio_estado_8d0864_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aviso",
            index=models.Index(
                fields=["usuario_cliente", "-creado_en"],
                name="notificacio_usuario_348e48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aviso",
            index=models.Index(
                fields=["evento", "-creado_en"], name="notificacio_evento_f42b5e_idx"
            ),
        ),
    ]
