# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("servicios", "0001_initial"),
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_inicio", models.DateTimeField(db_index=True)),
                ("fecha_hora_fin", models.DateTimeField(db_index=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Confirmación"),
                            ("CONFIRMADO", "Confirmado"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                            ("NO_SHOW", "No Show"),
                        ],
                        db_index=True,
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CON_SENA", "Con Seña"),
                            ("PAGADO", "Pagado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "monto_sena",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del servicio al momento de la reserva",
                        max_digits=10,
                    ),
                ),
                ("recordatorio_24h_enviado", models.BooleanField(default=False)),
                ("recordatorio_2h_enviado", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turnos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesional",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profesional asignado al turno",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turnos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="turnos",
                        to="servicios.servicio",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "ordering": ["-fecha_hora_inicio"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "fecha_hora_inicio"],
                        name="turnos_turn_sucursa_cbdf4d_idx",
                    ),
                    models.Index(
                        fields=["profesional", "fecha_hora_inicio"],
                        name="turnos_turn_profesi_e9ff5e_idx",
                    ),
                    models.Index(
                        fields=["cliente", "fecha_hora_inicio"],
                        name="turnos_turn_cliente_be3f57_idx",
                    ),
                    models.Index(
                        fields=["estado", "fecha_hora_inicio"],
                        name="turnos_turn_estado_9f1484_idx",
                    ),
                ],
            },
        ),
    ]
