# Generated by Django 4.2.7 on 2026-07-25 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turno",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Empleado que cargó el turno. Vacío si lo reservó el cliente desde la app",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="turnos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
