# Generated by Django 4.2.7 on 2025-11-27 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empleados", "0003_usuario_dias_laborales_usuario_horario_fin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True, help_text="Fecha del cierre de caja"
                    ),
                ),
                (
                    "total_sistema",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total según transacciones registradas en el sistema",
                        max_digits=10,
                    ),
                ),
                (
                    "efectivo_contado",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Efectivo físico contado al cierre",
                        max_digits=10,
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Diferencia entre sistema y físico (negativo = falta, positivo = sobra)",
                        max_digits=10,
                    ),
                ),
                (
                    "desglose_metodos",
                    models.JSONField(
                        default=dict,
                        help_text="Desglose por método de pago según sistema: {'CASH': 5000, 'DEBIT_CARD': 3000, ...}",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Notas o explicaciones sobre diferencias"
                    ),
                ),
                ("cerrado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        help_text="Empleado que realiza el cierre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cierres_caja",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cierres_caja",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de Caja",
                "verbose_name_plural": "Cierres de Caja",
                "ordering": ["-fecha", "-cerrado_en"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "fecha"],
                        name="mi_caja_cie_sucursa_10e108_idx",
                    ),
                    models.Index(
                        fields=["empleado", "fecha"],
                        name="mi_caja_cie_emplead_dcc50b_idx",
                    ),
                ],
                "unique_together": {("empleado", "fecha")},
            },
        ),
    ]
