# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0002_initial"),
        ("inventario", "0001_initial"),
        ("turnos", "0001_initial"),
        ("empleados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaTransaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("INGRESO", "Ingreso"), ("GASTO", "Gasto")],
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_transaccion",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Transacción",
                "verbose_name_plural": "Categorías de Transacciones",
                "ordering": ["tipo", "nombre"],
                "unique_together": {("sucursal", "nombre", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="CuentaPorCobrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monto_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_pendiente",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("fecha_pago_completo", models.DateField(blank=True, null=True)),
                ("descripcion", models.CharField(max_length=300)),
                ("notas", models.TextField(blank=True)),
                ("pagada", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_por_cobrar",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas_por_cobrar",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuentas_por_cobrar",
                        to="turnos.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta por Cobrar",
                "verbose_name_plural": "Cuentas por Cobrar",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO_SERVICIO", "Ingreso por Servicio"),
                            ("INGRESO_PRODUCTO", "Ingreso por Venta de Producto"),
                            ("INGRESO_OTRO", "Otro Ingreso"),
                            ("GASTO_SUELDO", "Gasto - Sueldo"),
                            ("GASTO_ALQUILER", "Gasto - Alquiler"),
                            ("GASTO_INSUMO", "Gasto - Insumos"),
                            ("GASTO_SERVICIO", "Gasto - Servicios (luz, agua, etc.)"),
                            ("GASTO_MARKETING", "Gasto - Marketing"),
                            ("GASTO_OTRO", "Otro Gasto"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto de la transacción",
                        max_digits=10,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TRANSFERENCIA", "Transferencia"),
                            ("TARJETA_DEBITO", "Tarjeta de Débito"),
                            ("TARJETA_CREDITO", "Tarjeta de Crédito"),
                            ("MERCADOPAGO", "MercadoPago"),
                            ("OTRO", "Otro"),
                        ],
                        default="EFECTIVO",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField(db_index=True)),
                ("descripcion", models.CharField(max_length=300)),
                ("notas", models.TextField(blank=True)),
                ("numero_comprobante", models.CharField(blank=True, max_length=50)),
                (
                    "archivo_comprobante",
                    models.FileField(blank=True, null=True, upload_to="comprobantes/"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones",
                        to="finanzas.categoriatransaccion",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente asociado (solo para ingresos)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones",
                        to="inventario.producto",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones",
                        to="turnos.turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-fecha", "-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "fecha"],
                        name="finanzas_tr_sucursa_31fb7f_idx",
                    ),
                    models.Index(
                        fields=["sucursal", "tipo", "fecha"],
                        name="finanzas_tr_sucursa_875659_idx",
                    ),
                ],
            },
        ),
    ]
