# Generated by Django 4.2.7 on 2025-11-18 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0002_initial"),
        ("turnos", "0001_initial"),
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empleados", "0001_initial"),
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount owed", max_digits=10
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount already paid",
                        max_digits=10,
                    ),
                ),
                (
                    "pending_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining amount to pay",
                        max_digits=10,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("full_payment_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_receivable",
                        to="turnos.turno",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_receivable",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_receivable",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Receivable",
                "verbose_name_plural": "Accounts Receivable",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INCOME_SERVICE", "Income from Service"),
                            ("INCOME_PRODUCT", "Income from Product Sale"),
                            ("INCOME_OTHER", "Other Income"),
                            ("EXPENSE", "Expense"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive)",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("TRANSFER", "Bank Transfer"),
                            ("DEBIT_CARD", "Debit Card"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("MERCADOPAGO", "MercadoPago"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF, JPG, or PNG file",
                        null=True,
                        upload_to="receipts/%Y/%m/",
                    ),
                ),
                (
                    "auto_generated",
                    models.BooleanField(
                        default=False,
                        help_text="If created automatically (e.g., from inventory)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="turnos.turno",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier for UI", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_category",
                    models.BooleanField(
                        default=False,
                        help_text="System categories cannot be deleted, only deactivated",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order in UI"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_categories",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="finanzas.transactioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Category",
                "verbose_name_plural": "Transaction Categories",
                "ordering": ["type", "order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="cuentaporcobrar",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="cuentaporcobrar",
            name="sucursal",
        ),
        migrations.RemoveField(
            model_name="cuentaporcobrar",
            name="turno",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="registrado_por",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="sucursal",
        ),
        migrations.RemoveField(
            model_name="transaccion",
            name="turno",
        ),
        migrations.DeleteModel(
            name="CategoriaTransaccion",
        ),
        migrations.DeleteModel(
            name="CuentaPorCobrar",
        ),
        migrations.DeleteModel(
            name="Transaccion",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                help_text="Category or subcategory of the transaction",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finanzas.transactioncategory",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated client (mainly for income)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_edited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="inventory_movement",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked inventory movement if auto-generated",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_transaction",
                to="inventario.movimientoinventario",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="inventario.producto",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="registered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_registered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="transactioncategory",
            index=models.Index(
                fields=["branch", "type", "is_active"],
                name="finanzas_tr_branch__b904b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactioncategory",
            index=models.Index(
                fields=["parent_category"], name="finanzas_tr_parent__03cc37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactioncategory",
            unique_together={("branch", "name", "type", "parent_category")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["branch", "date"], name="finanzas_tr_branch__57724b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["branch", "type", "date"], name="finanzas_tr_branch__ebf4f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["branch", "category", "date"],
                name="finanzas_tr_branch__3d118e_idx",
            ),
        ),
    ]
