# Generated by Django 4.2.7 on 2025-11-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0003_fix_codigo_barras_null"),
        ("clientes", "0002_initial"),
        ("finanzas", "0002_accountreceivable_transaction_transactioncategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountreceivable",
            options={
                "ordering": ["-issue_date"],
                "verbose_name": "Cuenta por Cobrar",
                "verbose_name_plural": "Cuentas por Cobrar",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
            },
        ),
        migrations.AlterModelOptions(
            name="transactioncategory",
            options={
                "ordering": ["type", "order", "name"],
                "verbose_name": "Categoría de Transacción",
                "verbose_name_plural": "Categorías de Transacciones",
            },
        ),
        migrations.AlterField(
            model_name="accountreceivable",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Monto ya pagado", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="accountreceivable",
            name="pending_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Monto restante por pagar", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="accountreceivable",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Monto total adeudado", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto de la transacción (siempre positivo)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="auto_generated",
            field=models.BooleanField(
                default=False,
                help_text="Si fue creado automáticamente (ej: desde inventario)",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                help_text="Categoría o subcategoría de la transacción",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finanzas.transactioncategory",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Cliente asociado (principalmente para ingresos)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="inventory_movement",
            field=models.OneToOneField(
                blank=True,
                help_text="Movimiento de inventario vinculado si fue auto-generado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_transaction",
                to="inventario.movimientoinventario",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("TRANSFER", "Transferencia"),
                    ("DEBIT_CARD", "Tarjeta de Débito"),
                    ("CREDIT_CARD", "Tarjeta de Crédito"),
                    ("MERCADOPAGO", "MercadoPago"),
                    ("OTHER", "Otro"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                help_text="Archivo PDF, JPG o PNG",
                null=True,
                upload_to="receipts/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCOME_SERVICE", "Ingreso por Servicio"),
                    ("INCOME_PRODUCT", "Ingreso por Venta de Producto"),
                    ("INCOME_OTHER", "Otro Ingreso"),
                    ("EXPENSE", "Gasto"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Código de color hexadecimal para mostrar en UI",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Identificador de ícono para UI", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="is_system_category",
            field=models.BooleanField(
                default=False,
                help_text="Las categorías del sistema no pueden eliminarse, solo desactivarse",
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Orden de visualización en UI"
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría padre para estructura jerárquica",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="finanzas.transactioncategory",
            ),
        ),
        migrations.AlterField(
            model_name="transactioncategory",
            name="type",
            field=models.CharField(
                choices=[("INCOME", "Ingreso"), ("EXPENSE", "Gasto")], max_length=10
            ),
        ),
    ]
