# Generated by Django 4.2.7 on 2025-11-27 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finanzas", "0003_add_alquiler_maquina"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Dirección IP desde donde se creó la transacción",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="Información del navegador/dispositivo usado"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuario que editó la transacción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_edited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="registered_by",
            field=models.ForeignKey(
                help_text="Usuario que registró esta transacción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_registered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
