# Generated by Django 4.2.7 on 2026-08-05 20:49

import apps.integraciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finanzas", "0006_transaction_service"),
        ("empleados", "0003_usuario_dias_laborales_usuario_horario_fin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContoIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="URL base de la API de Conto, sin barra final"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token de solo lectura generado en Conto. No se muestra en la API",
                        max_length=255,
                    ),
                ),
                (
                    "conto_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Se completa automáticamente al verificar la vinculación",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "conto_account_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la cuenta en Conto, para que un humano confirme la vinculación",
                        max_length=200,
                    ),
                ),
                (
                    "link_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última vez que se validó la identidad contra Conto",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Se activa recién cuando la vinculación fue verificada",
                    ),
                ),
                (
                    "default_payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("BANK_TRANSFER", "Transferencia"),
                            ("DEBIT_CARD", "Tarjeta de Débito"),
                            ("CREDIT_CARD", "Tarjeta de Crédito"),
                            ("MERCADOPAGO", "MercadoPago"),
                            ("OTHER", "Otro"),
                        ],
                        default="MERCADOPAGO",
                        help_text="Se usa cuando Conto no informa el medio de pago real",
                        max_length=20,
                    ),
                ),
                (
                    "channels_to_import",
                    models.JSONField(
                        default=apps.integraciones.models.default_import_channels,
                        help_text="Canales de Conto a importar. Por defecto solo 'tiendanube'",
                    ),
                ),
                (
                    "create_missing_clients",
                    models.BooleanField(
                        default=True,
                        help_text="Crear el cliente si no existe en este centro",
                    ),
                ),
                (
                    "create_missing_products",
                    models.BooleanField(
                        default=True,
                        help_text="Crear el producto si el SKU no existe en la sucursal. Conto informa costo y precio, así que el producto nace completo",
                    ),
                ),
                (
                    "import_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="No importar ventas anteriores a esta fecha. Obligatorio para la primera corrida: evita traer años de histórico sin querer. Para ampliar el histórico después, moverla hacia atrás y limpiar 'última sincronización de ventas'",
                        null=True,
                    ),
                ),
                ("last_stock_sync", models.DateTimeField(blank=True, null=True)),
                ("last_sales_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Sucursal a la que se imputan las ventas y el stock de Conto",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conto_integrations",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "center",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conto_integration",
                        to="empleados.centroestetica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integración con Conto",
                "verbose_name_plural": "Integraciones con Conto",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ContoSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_id", models.CharField(db_index=True, max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("SALE", "Venta"), ("CREDIT_NOTE", "Nota de Crédito")],
                        default="SALE",
                        max_length=20,
                    ),
                ),
                (
                    "related_voucher_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Para notas de crédito: voucher de la venta que reversan",
                        max_length=100,
                    ),
                ),
                (
                    "external_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Número de orden en Tienda Nube o Mercado Libre",
                        max_length=100,
                    ),
                ),
                ("channel", models.CharField(db_index=True, max_length=50)),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la venta según Conto, ya resuelta en hora de Argentina",
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Respuesta cruda de Conto. Permite reprocesar sin volver a consultar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PROCESSED", "Procesada"),
                            ("ERROR", "Error"),
                            ("SKIPPED", "Omitida"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="integraciones.contointegration",
                    ),
                ),
                (
                    "transactions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Transacciones generadas a partir de este voucher",
                        related_name="conto_sales",
                        to="finanzas.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta de Conto",
                "verbose_name_plural": "Ventas de Conto",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "status"],
                        name="integracion_integra_a95be1_idx",
                    ),
                    models.Index(
                        fields=["integration", "date"],
                        name="integracion_integra_77d8da_idx",
                    ),
                ],
                "unique_together": {("integration", "voucher_id")},
            },
        ),
    ]
