# Generated by Django 4.2.7 on 2026-08-06 16:05

import apps.integraciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0003_usuario_dias_laborales_usuario_horario_fin_and_more"),
        ("integraciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contointegration",
            name="base_url",
            field=models.URLField(
                help_text="URL base de la API de Conto, sin barra final",
                verbose_name="URL de Conto",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="branch",
            field=models.ForeignKey(
                help_text="Sucursal a la que se imputan las ventas y el stock de Conto",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conto_integrations",
                to="empleados.sucursal",
                verbose_name="Sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="center",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conto_integration",
                to="empleados.centroestetica",
                verbose_name="Centro estética",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="channels_to_import",
            field=models.JSONField(
                default=apps.integraciones.models.default_import_channels,
                help_text="Canales de Conto a importar. Por defecto solo 'tiendanube'",
                verbose_name="Canales a importar",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="conto_account_id",
            field=models.CharField(
                blank=True,
                help_text="Se completa automáticamente al verificar la vinculación",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="ID de cuenta en Conto",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="conto_account_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre de la cuenta en Conto, para que un humano confirme la vinculación",
                max_length=200,
                verbose_name="Nombre de cuenta en Conto",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="create_missing_clients",
            field=models.BooleanField(
                default=True,
                help_text="Crear el cliente si no existe en este centro",
                verbose_name="Crear clientes faltantes",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="create_missing_products",
            field=models.BooleanField(
                default=True,
                help_text="Crear el producto si el SKU no existe en la sucursal. Conto informa costo y precio, así que el producto nace completo",
                verbose_name="Crear productos faltantes",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="default_payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("BANK_TRANSFER", "Transferencia"),
                    ("DEBIT_CARD", "Tarjeta de Débito"),
                    ("CREDIT_CARD", "Tarjeta de Crédito"),
                    ("MERCADOPAGO", "MercadoPago"),
                    ("OTHER", "Otro"),
                ],
                default="MERCADOPAGO",
                help_text="Se usa cuando Conto no informa el medio de pago real",
                max_length=20,
                verbose_name="Medio de pago por defecto",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="import_from",
            field=models.DateTimeField(
                blank=True,
                help_text="No importar ventas anteriores a esta fecha. Obligatorio para la primera corrida: evita traer años de histórico sin querer. Para ampliar el histórico después, moverla hacia atrás y limpiar 'última sincronización de ventas'",
                null=True,
                verbose_name="Importar ventas desde",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Se activa recién cuando la vinculación fue verificada",
                verbose_name="Activa",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="last_sales_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última sincronización de ventas"
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="last_stock_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última sincronización de stock"
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="link_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Última vez que se validó la identidad contra Conto",
                null=True,
                verbose_name="Vinculación verificada el",
            ),
        ),
        migrations.AlterField(
            model_name="contointegration",
            name="token",
            field=models.CharField(
                help_text="Token de solo lectura generado en Conto. No se muestra en la API",
                max_length=255,
                verbose_name="Token",
            ),
        ),
    ]
