# Generated by Django 4.2.7 on 2026-08-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integraciones", "0002_alter_contointegration_base_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contosale",
            name="total_discrepancy",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Diferencia entre la suma de las líneas y el total informado por Conto. Vacío significa que cuadra",
                max_digits=12,
                null=True,
                verbose_name="Descuadre contra el total",
            ),
        ),
    ]
