# Generated by Django 4.2.7 on 2026-08-15 13:11

from django.db import migrations, models

# Conto's keys, and the columns they land in.
RAW_KEYS = ('origen_venta', 'app_origen', 'cupon', 'descuento_cupon')
RAW_COLUMNS = ['sale_origin', 'app_origin', 'coupon_code', 'coupon_discount']


def backfill_from_payload(apps, schema_editor):
    """
    Recover the fields from the payloads already stored.

    They started arriving in August 2026 and every voucher keeps its raw
    payload, so the vouchers imported between then and this migration already
    carry them — they were only unreachable without parsing JSON.
    """
    from apps.integraciones.sync import raw_origin_fields

    ContoSale = apps.get_model('integraciones', 'ContoSale')

    pending = []
    for sale in ContoSale.objects.all().iterator():
        payload = sale.payload
        if not isinstance(payload, dict) or not any(k in payload for k in RAW_KEYS):
            continue
        for name, value in raw_origin_fields(payload).items():
            setattr(sale, name, value)
        pending.append(sale)
        if len(pending) >= 500:
            ContoSale.objects.bulk_update(pending, RAW_COLUMNS)
            pending = []

    if pending:
        ContoSale.objects.bulk_update(pending, RAW_COLUMNS)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("integraciones", "0003_contosale_total_discrepancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="contosale",
            name="app_origin",
            field=models.CharField(
                blank=True,
                help_text="Campo 'app_origen' de Conto, crudo: qué app de Tienda Nube creó la orden, si fue creada por una",
                max_length=100,
                verbose_name="App de origen",
            ),
        ),
        migrations.AddField(
            model_name="contosale",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Campo 'cupon' de Conto, crudo. Con más de un cupón vienen los códigos separados por coma",
                max_length=200,
                verbose_name="Cupón",
            ),
        ),
        migrations.AddField(
            model_name="contosale",
            name="coupon_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Campo 'descuento_cupon' de Conto. Vacío significa que Conto no informó el campo, que no es lo mismo que un descuento de 0",
                max_digits=12,
                null=True,
                verbose_name="Descuento por cupón",
            ),
        ),
        migrations.AddField(
            model_name="contosale",
            name="sale_origin",
            field=models.CharField(
                blank=True,
                help_text="Campo 'origen_venta' de Conto, crudo: de dónde dice Tienda Nube que viene la orden (store, api, meli, form, pos)",
                max_length=50,
                verbose_name="Origen de la venta",
            ),
        ),
        migrations.RunPython(backfill_from_payload, noop_reverse),
    ]
