# Generated by Django 4.2.7 on 2026-08-16 00:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0004_alter_centroestetica_logo"),
        ("integraciones", "0004_contosale_coupon_and_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiendanubeIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_id",
                    models.CharField(
                        help_text="El `user_id` que devuelve el OAuth de Tienda Nube",
                        max_length=50,
                        unique=True,
                        verbose_name="ID de tienda",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        blank=True,
                        help_text="Para que un humano confirme que se vinculó la tienda correcta",
                        max_length=200,
                        verbose_name="Nombre de la tienda",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token de Tienda Nube. No se muestra en la API",
                        max_length=255,
                        verbose_name="Token",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text="Permisos que el centro autorizó al instalar la app",
                        max_length=300,
                        verbose_name="Permisos",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se desactiva sola cuando el centro desinstala la app",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Instalada el"
                    ),
                ),
                (
                    "uninstalled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Desinstalada el"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiendanube_integration",
                        to="empleados.centroestetica",
                        verbose_name="Centro estética",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integración con Tienda Nube",
                "verbose_name_plural": "Integraciones con Tienda Nube",
                "ordering": ["id"],
            },
        ),
    ]
