# Generated by Django 4.2.7 on 2026-08-16 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0009_segmento_app"),
        ("integraciones", "0005_tiendanubeintegration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiendanubeintegration",
            name="coupons_combine_with_other_discounts",
            field=models.BooleanField(
                default=True,
                help_text="Si está activo, el descuento de la app se suma a los del medio de pago. Si no, lo reemplaza",
                verbose_name="Los cupones se combinan con otras promociones",
            ),
        ),
        migrations.CreateModel(
            name="CuponApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código con prefijo APP-, impredecible y de un solo uso",
                        max_length=30,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje que se le aplicó, resuelto por el segmento de la clienta",
                        max_digits=5,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "tiendanube_coupon_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Necesario para borrarlo cuando vence sin usarse",
                        max_length=50,
                        verbose_name="ID en Tienda Nube",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Emitido"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Vence")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Se completa al importar la venta que lo trae",
                        null=True,
                        verbose_name="Usado",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo lo borró la limpieza por haber vencido sin usarse",
                        null=True,
                        verbose_name="Borrado de Tienda Nube",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cupones_app",
                        to="clientes.cliente",
                        verbose_name="Clienta",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cupones",
                        to="integraciones.tiendanubeintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cupón de la app",
                "verbose_name_plural": "Cupones de la app",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at", "used_at", "revoked_at"],
                        name="integracion_expires_878647_idx",
                    )
                ],
            },
        ),
    ]
