# Generated by Django 4.2.7 on 2026-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integraciones", "0006_cupon_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiendanubeintegration",
            name="store_url",
            field=models.URLField(
                blank=True,
                help_text="Dirección pública, para armar el carrito y el checkout",
                verbose_name="URL de la tienda",
            ),
        ),
    ]
