# Generated by Django 4.2.7 on 2026-08-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integraciones", "0007_tiendanubeintegration_store_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contosale",
            name="cupon_app",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargado al importar, cuando el código de la venta es uno nuestro",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="integraciones.cuponapp",
                verbose_name="Cupón de la app",
            ),
        ),
    ]
