# Generated by Django 4.2.7 on 2026-08-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0004_alter_centroestetica_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integraciones", "0008_contosale_cupon_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="TiendanubePrivacyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="ID de tienda"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("store/redact", "Borrado de la tienda"),
                            ("customers/redact", "Borrado de datos de un comprador"),
                            (
                                "customers/data_request",
                                "Pedido de datos de un comprador",
                            ),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Evento",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Lo que mandó Tienda Nube, crudo",
                        verbose_name="Contenido",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Recibido"
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo se le respondió al centro. Los de la tienda se resuelven solos; los de un comprador los cierra una persona",
                        null=True,
                        verbose_name="Resuelto",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Qué se hizo con el pedido",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_requests",
                        to="integraciones.tiendanubeintegration",
                        verbose_name="Integración",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de privacidad de Tienda Nube",
                "verbose_name_plural": "Pedidos de privacidad de Tienda Nube",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["handled_at", "received_at"],
                        name="integracion_handled_15a036_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TiendanubeInstallIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Ventana para completar la instalación. Corta a propósito: es lo que hace que solo haya un intento abierto por vez",
                        verbose_name="Vence",
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo la reclamó el callback. Una intención sirve una sola vez",
                        null=True,
                        verbose_name="Usada",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiendanube_install_intents",
                        to="empleados.centroestetica",
                        verbose_name="Centro estética",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Iniciada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instalación de Tienda Nube iniciada",
                "verbose_name_plural": "Instalaciones de Tienda Nube iniciadas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["consumed_at", "expires_at"],
                        name="integracion_consume_99cbea_idx",
                    )
                ],
            },
        ),
    ]
