# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Color en formato hexadecimal para visualización en calendario",
                        max_length=7,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_servicio",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Servicio",
                "verbose_name_plural": "Categorías de Servicios",
                "ordering": ["nombre"],
                "unique_together": {("sucursal", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código interno del servicio",
                        max_length=50,
                    ),
                ),
                (
                    "duracion_minutos",
                    models.PositiveIntegerField(
                        help_text="Duración en minutos del servicio"
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "comision_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje de comisión por defecto",
                        max_digits=5,
                    ),
                ),
                ("requiere_profesional", models.BooleanField(default=True)),
                (
                    "requiere_equipamiento",
                    models.CharField(
                        blank=True,
                        help_text="Equipamiento o máquina necesaria",
                        max_length=200,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(
                        default="#10B981",
                        help_text="Color para calendario (hereda de categoría si existe)",
                        max_length=7,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios",
                        to="servicios.categoriaservicio",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["sucursal", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "activo"],
                        name="servicios_s_sucursa_52620e_idx",
                    )
                ],
            },
        ),
    ]
