# Generated by Django 4.2.7 on 2025-11-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0002_add_sueldo_mensual"),
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaquinaAlquilada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la máquina (ej: Liposonix Pro)",
                        max_length=200,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "costo_diario",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo de alquiler por DÍA",
                        max_digits=10,
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(
                        blank=True,
                        help_text="Empresa que alquila la máquina",
                        max_length=200,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maquinas_alquiladas",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Máquina Alquilada",
                "verbose_name_plural": "Máquinas Alquiladas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="servicio",
            name="maquina_alquilada",
            field=models.ForeignKey(
                blank=True,
                help_text="Máquina alquilada necesaria para este servicio",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servicios",
                to="servicios.maquinaalquilada",
            ),
        ),
        migrations.AddIndex(
            model_name="maquinaalquilada",
            index=models.Index(
                fields=["sucursal", "activa"], name="servicios_m_sucursa_8f7ccd_idx"
            ),
        ),
    ]
