# Generated by Django 4.2.7 on 2025-11-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empleados", "0002_add_sueldo_mensual"),
        ("finanzas", "0003_add_alquiler_maquina"),
        ("servicios", "0002_add_maquinas_alquiladas"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlquilerMaquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(help_text="Fecha del alquiler")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                            ("COBRADO", "Cobrado"),
                        ],
                        default="PROGRAMADO",
                        max_length=20,
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo del alquiler (se copia del costo_diario de la máquina)",
                        max_digits=10,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alquileres_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maquina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alquileres",
                        to="servicios.maquinaalquilada",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alquileres_maquinas",
                        to="empleados.sucursal",
                    ),
                ),
                (
                    "transaccion_gasto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transacción de gasto generada",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alquiler_maquina",
                        to="finanzas.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alquiler de Máquina",
                "verbose_name_plural": "Alquileres de Máquinas",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["sucursal", "fecha", "estado"],
                        name="servicios_a_sucursa_5b0d1b_idx",
                    ),
                    models.Index(
                        fields=["maquina", "fecha"],
                        name="servicios_a_maquina_e22e8e_idx",
                    ),
                ],
                "unique_together": {("maquina", "fecha", "sucursal")},
            },
        ),
    ]
