# Generated by Django 4.2.7 on 2026-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicios", "0004_maquinaalquilada_fecha_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="dias_reserva",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Días en que el cliente puede reservar ESTE servicio desde la app (ej: ['viernes', 'sabado']). Vacío = usa los días generales de la app (ver DIAS_RESERVA_APP en apps.turnos.services). Reemplaza la regla general, no la complementa.",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="reservable_por_cliente",
            field=models.BooleanField(
                default=False,
                help_text="¿El cliente puede reservar este servicio desde la app? Se activa a mano: solo los servicios que el centro puede preparar de un día para el otro. El staff siempre puede agendarlo desde el CRM.",
            ),
        ),
    ]
