# Generated by Django 4.2.7 on 2026-07-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicios", "0005_servicio_dias_reserva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="beneficios",
            field=models.TextField(
                blank=True,
                help_text="Qué gana el cliente con el tratamiento. Se muestra en la ficha de la app.",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Link al video del tratamiento (Instagram, YouTube, TikTok). Se abre desde la ficha de la app.",
                max_length=500,
            ),
        ),
    ]
