# Generated by Django 4.2.7 on 2025-11-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="sueldo_mensual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sueldo mensual del empleado",
                max_digits=10,
                null=True,
            ),
        ),
    ]
