# Generated by Django 4.2.7 on 2025-11-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0002_add_sueldo_mensual"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="dias_laborales",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de días laborales: ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="horario_fin",
            field=models.TimeField(
                blank=True,
                help_text="Hora de fin del día laboral (ej: 18:00)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="horario_inicio",
            field=models.TimeField(
                blank=True,
                help_text="Hora de inicio del día laboral (ej: 09:00)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="intervalo_minutos",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Intervalo en minutos para la agenda (granularidad de slots)",
            ),
        ),
    ]
