# Generated by Django 4.2.7 on 2026-08-08 16:56

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0003_usuario_dias_laborales_usuario_horario_fin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centroestetica",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storage.storage_publico,
                upload_to="logos/",
            ),
        ),
    ]
