/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/mi-rutina`; params?: Router.UnknownInputParams; } | { pathname: `/servicios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/bienvenida` | `/bienvenida`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/codigo` | `/codigo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registro` | `/registro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/promos` | `/promos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservar` | `/reservar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/turnos` | `/turnos`; params?: Router.UnknownInputParams; } | { pathname: `/servicio/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/mi-rutina`; params?: Router.UnknownOutputParams; } | { pathname: `/servicios`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/bienvenida` | `/bienvenida`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/codigo` | `/codigo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/registro` | `/registro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/promos` | `/promos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reservar` | `/reservar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/turnos` | `/turnos`; params?: Router.UnknownOutputParams; } | { pathname: `/servicio/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/mi-rutina${`?${string}` | `#${string}` | ''}` | `/servicios${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/bienvenida${`?${string}` | `#${string}` | ''}` | `/bienvenida${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/codigo${`?${string}` | `#${string}` | ''}` | `/codigo${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/registro${`?${string}` | `#${string}` | ''}` | `/registro${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/promos${`?${string}` | `#${string}` | ''}` | `/promos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reservar${`?${string}` | `#${string}` | ''}` | `/reservar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/turnos${`?${string}` | `#${string}` | ''}` | `/turnos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/mi-rutina`; params?: Router.UnknownInputParams; } | { pathname: `/servicios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/bienvenida` | `/bienvenida`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/codigo` | `/codigo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registro` | `/registro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/promos` | `/promos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reservar` | `/reservar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/turnos` | `/turnos`; params?: Router.UnknownInputParams; } | `/servicio/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/servicio/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
