# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("telefono_alternativo", models.CharField(blank=True, max_length=20)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("provincia", models.CharField(blank=True, max_length=100)),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("PASAPORTE", "Pasaporte"),
                            ("OTRO", "Otro"),
                        ],
                        default="DNI",
                        max_length=10,
                    ),
                ),
                ("numero_documento", models.CharField(blank=True, max_length=20)),
                (
                    "alergias",
                    models.TextField(blank=True, help_text="Alergias o sensibilidades"),
                ),
                ("contraindicaciones", models.TextField(blank=True)),
                ("notas_medicas", models.TextField(blank=True)),
                (
                    "preferencias",
                    models.TextField(blank=True, help_text="Preferencias del cliente"),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="clientes/"),
                ),
                ("acepta_promociones", models.BooleanField(default=True)),
                ("acepta_whatsapp", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("ultima_visita", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("observaciones", models.TextField(blank=True)),
                ("resultado", models.TextField(blank=True)),
                (
                    "foto_antes",
                    models.ImageField(
                        blank=True, null=True, upload_to="tratamientos/antes/"
                    ),
                ),
                (
                    "foto_despues",
                    models.ImageField(
                        blank=True, null=True, upload_to="tratamientos/despues/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Cliente",
                "verbose_name_plural": "Historiales de Clientes",
                "ordering": ["-fecha"],
            },
        ),
    ]
