# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("servicios", "0001_initial"),
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialcliente",
            name="profesional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historiales_atendidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialcliente",
            name="servicio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="historiales",
                to="servicios.servicio",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="centro_estetica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="empleados.centroestetica",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["centro_estetica", "apellido"],
                name="clientes_cl_centro__84f5f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["centro_estetica", "telefono"],
                name="clientes_cl_centro__30d294_idx",
            ),
        ),
    ]
