# Generated by Django 4.2.7 on 2025-11-25 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="adiposidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAJA", "Baja"),
                    ("MEDIA", "Media"),
                    ("ALTA", "Alta"),
                    ("NO_APLICA", "No aplica"),
                ],
                help_text="Adiposidad localizada",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="brillo",
            field=models.CharField(
                blank=True,
                choices=[("BAJO", "Bajo"), ("MEDIO", "Medio"), ("ALTO", "Alto")],
                help_text="Nivel de brillo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cancer_historial",
            field=models.BooleanField(
                default=False, help_text="¿Cáncer actual o antecedente?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="celulitis_grado",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")],
                help_text="Grado de celulitis (0-3)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="celulitis_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDEMATOSA", "Edematosa"),
                    ("FIBROSA", "Fibrosa"),
                    ("BLANDA", "Blanda"),
                    ("MIXTA", "Mixta"),
                    ("NO_APLICA", "No aplica"),
                ],
                help_text="Tipo de celulitis",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="detalle_general",
            field=models.TextField(
                blank=True, help_text="Aclaraciones adicionales generales"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="diagnostico_corporal",
            field=models.TextField(
                blank=True, help_text="Diagnóstico corporal resumen"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="diagnostico_facial",
            field=models.TextField(blank=True, help_text="Diagnóstico facial resumen"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="embarazo_lactancia",
            field=models.BooleanField(
                default=False, help_text="¿Embarazo o lactancia?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estado_piel",
            field=models.TextField(
                blank=True,
                help_text="Estado de piel: deshidratada, sensible, rosácea, manchas, acné, etc.",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estrias",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO", "No"),
                    ("BLANCAS", "Blancas"),
                    ("ROJAS", "Rojas"),
                    ("MIXTAS", "Mixtas"),
                ],
                help_text="Estrías",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="flacidez",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEVE", "Leve"),
                    ("MODERADA", "Moderada"),
                    ("MARCADA", "Marcada"),
                    ("NO_APLICA", "No aplica"),
                ],
                help_text="Flacidez corporal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="herpes_historial",
            field=models.BooleanField(default=False, help_text="¿Historial de herpes?"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="marcapasos_implantes",
            field=models.BooleanField(
                default=False, help_text="¿Marcapasos o implantes metálicos?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="medicacion_actual",
            field=models.BooleanField(
                default=False, help_text="¿Toma medicación actual?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="medicacion_detalle",
            field=models.TextField(
                blank=True, help_text="Detalle de medicación actual"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="motivo_consulta",
            field=models.TextField(
                blank=True, help_text="Motivo principal de consulta"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="objetivo_principal",
            field=models.CharField(
                blank=True, help_text="Objetivo principal en una frase", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="observaciones_corporales",
            field=models.TextField(blank=True, help_text="Observaciones corporales"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="observaciones_faciales",
            field=models.TextField(
                blank=True, help_text="Observaciones de zonas puntuales"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="poros",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FINOS", "Finos"),
                    ("MEDIOS", "Medios"),
                    ("DILATADOS", "Dilatados"),
                    ("MIXTO", "Mixto"),
                ],
                help_text="Estado de poros",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="retencion_liquidos",
            field=models.BooleanField(
                default=False, help_text="¿Retención de líquidos?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tatuajes_zona_tratamiento",
            field=models.BooleanField(
                default=False, help_text="¿Tatuajes en zona a tratar?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tatuajes_zonas",
            field=models.TextField(blank=True, help_text="Zonas con tatuajes"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="textura",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNIFORME", "Uniforme"),
                    ("ASPERA", "Áspera"),
                    ("DESCAMACION", "Descamación"),
                    ("MIXTA", "Mixta"),
                ],
                help_text="Textura de la piel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tiene_alergias",
            field=models.BooleanField(default=False, help_text="¿Tiene alergias?"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo_piel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NORMAL", "Normal"),
                    ("SECA", "Seca"),
                    ("MIXTA", "Mixta"),
                    ("GRASA", "Grasa"),
                    ("NO_DETERMINADO", "No determinado"),
                ],
                help_text="Tipo de piel",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tratamientos_previos",
            field=models.BooleanField(
                default=False, help_text="¿Tratamientos estéticos previos?"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tratamientos_previos_detalle",
            field=models.TextField(
                blank=True, help_text="Detalle de tratamientos previos"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="zonas_tratar",
            field=models.TextField(blank=True, help_text="Zonas corporales a tratar"),
        ),
        migrations.CreateModel(
            name="RutinaCuidado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rutina_diurna_pasos",
                    models.TextField(blank=True, help_text="Pasos de la rutina diurna"),
                ),
                (
                    "rutina_diurna_productos",
                    models.TextField(
                        blank=True,
                        help_text="Productos recomendados para rutina diurna",
                    ),
                ),
                (
                    "rutina_nocturna_pasos",
                    models.TextField(
                        blank=True, help_text="Pasos de la rutina nocturna"
                    ),
                ),
                (
                    "rutina_nocturna_productos",
                    models.TextField(
                        blank=True,
                        help_text="Productos recomendados para rutina nocturna",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "activa",
                    models.BooleanField(
                        default=True, help_text="¿Es la rutina activa actual?"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutinas_cuidado",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rutinas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rutina de Cuidado",
                "verbose_name_plural": "Rutinas de Cuidado",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="PlanTratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tratamiento_sugerido",
                    models.TextField(help_text="Tratamiento sugerido (resumen)"),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: semanal / quincenal / mensual",
                        max_length=100,
                    ),
                ),
                (
                    "sesiones_estimadas",
                    models.IntegerField(
                        blank=True, help_text="Número de sesiones estimadas", null=True
                    ),
                ),
                (
                    "indicaciones",
                    models.TextField(
                        blank=True,
                        help_text="Indicaciones / homecare / post tratamiento",
                    ),
                ),
                (
                    "proximo_turno",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora del próximo turno",
                        null=True,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes_tratamiento",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Tratamiento",
                "verbose_name_plural": "Planes de Tratamiento",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="NotaCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_nota",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("RECORDATORIO", "Recordatorio"),
                            ("OBSERVACION", "Observación"),
                            ("IMPORTANTE", "Importante"),
                            ("SEGUIMIENTO", "Seguimiento"),
                        ],
                        default="GENERAL",
                        help_text="Tipo de nota",
                        max_length=20,
                    ),
                ),
                ("contenido", models.TextField(help_text="Contenido de la nota")),
                (
                    "visible_para",
                    models.CharField(
                        choices=[
                            ("TODOS", "Todos"),
                            ("SOLO_ADMIN", "Solo Admin"),
                            ("SOLO_AUTOR", "Solo profesional que creó"),
                        ],
                        default="TODOS",
                        help_text="Visibilidad de la nota",
                        max_length=20,
                    ),
                ),
                (
                    "destacada",
                    models.BooleanField(
                        default=False, help_text="¿Nota importante destacada?"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Cliente",
                "verbose_name_plural": "Notas de Clientes",
                "ordering": ["-destacada", "-creado_en"],
            },
        ),
    ]
