# Generated by Django 4.2.7 on 2026-07-17 09:58

import apps.clientes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0003_cliente_adiposidad_cliente_brillo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("apellido", models.CharField(blank=True, max_length=100)),
                ("email_verificado", models.BooleanField(default=False)),
                (
                    "push_token",
                    models.CharField(
                        blank=True,
                        help_text="Expo push token (ExponentPushToken[...]) para notificaciones",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Usuario de App (Cliente)",
                "verbose_name_plural": "Usuarios de App (Clientes)",
                "ordering": ["email"],
            },
            managers=[
                ("objects", apps.clientes.models.UsuarioClienteManager()),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono_normalizado",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name="VinculacionCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metodo_vinculacion",
                    models.CharField(
                        choices=[
                            ("CODIGO_INVITACION", "Código de invitación"),
                            ("INVITACION_STAFF", "Invitación manual por staff"),
                            ("REGISTRO_NUEVO", "Registro como cliente nuevo"),
                            ("MERGE_MANUAL", "Consolidación manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vinculado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculaciones",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "usuario_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculaciones",
                        to="clientes.usuariocliente",
                    ),
                ),
                (
                    "vinculado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vinculaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculación de Cliente",
                "verbose_name_plural": "Vinculaciones de Clientes",
                "ordering": ["-vinculado_en"],
                "unique_together": {("usuario_cliente", "cliente")},
            },
        ),
        migrations.AddField(
            model_name="usuariocliente",
            name="clientes",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios_app",
                through="clientes.VinculacionCliente",
                to="clientes.cliente",
            ),
        ),
        migrations.CreateModel(
            name="CodigoInvitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=16, unique=True)),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                ("expira_en", models.DateTimeField()),
                ("usado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_invitacion",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codigos_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codigos_usados",
                        to="clientes.usuariocliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Invitación",
                "verbose_name_plural": "Códigos de Invitación",
                "ordering": ["-generado_en"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "usado_en"],
                        name="clientes_co_cliente_b83b15_idx",
                    )
                ],
            },
        ),
    ]
