# Generated by Django 4.2.7 on 2026-07-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0005_producto_contenido_ml_and_more"),
        ("clientes", "0005_backfill_telefono_normalizado"),
    ]

    operations = [
        migrations.CreateModel(
            name="RutinaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "momento",
                    models.CharField(
                        choices=[("DIURNA", "Diurna"), ("NOCTURNA", "Nocturna")],
                        max_length=10,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "paso",
                    models.CharField(
                        blank=True,
                        help_text="Descripción del paso (ej: Limpieza, Serum, Protector solar)",
                        max_length=200,
                    ),
                ),
                (
                    "producto_texto",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del producto si no está en el catálogo",
                        max_length=200,
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True, help_text="Indicación adicional", max_length=300
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Producto del catálogo (opcional). Habilita precio/foto/compra.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rutina_items",
                        to="inventario.producto",
                    ),
                ),
                (
                    "rutina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="clientes.rutinacuidado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de rutina",
                "verbose_name_plural": "Ítems de rutina",
                "ordering": ["momento", "orden", "id"],
            },
        ),
    ]
