# Generated by Django 4.2.7 on 2026-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0006_rutinaitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vinculacioncliente",
            name="metodo_vinculacion",
            field=models.CharField(
                choices=[
                    ("CODIGO_INVITACION", "Código de invitación"),
                    ("INVITACION_STAFF", "Invitación manual por staff"),
                    ("REGISTRO_NUEVO", "Registro como cliente nuevo"),
                    ("AUTO_MATCH", "Match automático al registrarse"),
                    ("MERGE_MANUAL", "Consolidación manual"),
                ],
                max_length=20,
            ),
        ),
    ]
