# Generated by Django 4.2.7 on 2026-08-15 14:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models

# Arranca en 0: que exista el registro es una decisión de diseño (§5.8 pide un
# segmento general), pero cuánto descuenta es una decisión del centro, y encima
# depende de si se apila con el 10% de transferencia (§7.2). En 0 no cambia
# ningún precio hasta que alguien lo edite.
NOMBRE_SEGMENTO_GENERAL = 'General de la app'


def crear_segmento_general(apps, schema_editor):
    """Un segmento general por centro, para que el descuento de la app sea un campo y no un alta."""
    CentroEstetica = apps.get_model('empleados', 'CentroEstetica')
    SegmentoApp = apps.get_model('clientes', 'SegmentoApp')

    for centro in CentroEstetica.objects.all().iterator():
        SegmentoApp.objects.get_or_create(
            centro_estetica=centro,
            es_predeterminado=True,
            defaults={'nombre': NOMBRE_SEGMENTO_GENERAL},
        )


def borrar_segmento_general(apps, schema_editor):
    """Solo los que quedaron intactos: si alguien los editó, son datos del centro."""
    SegmentoApp = apps.get_model('clientes', 'SegmentoApp')
    SegmentoApp.objects.filter(
        es_predeterminado=True,
        nombre=NOMBRE_SEGMENTO_GENERAL,
        porcentaje_descuento=0,
    ).delete()
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0004_alter_centroestetica_logo"),
        ("clientes", "0008_remove_usuariocliente_push_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentoApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje que se le descuenta a las clientas de este segmento",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "es_predeterminado",
                    models.BooleanField(
                        default=False,
                        help_text="El descuento que le corresponde a toda clienta sin segmento propio",
                        verbose_name="Es el general de la app",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "centro_estetica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentos_app",
                        to="empleados.centroestetica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmento de la app",
                "verbose_name_plural": "Segmentos de la app",
                "ordering": ["-es_predeterminado", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="segmento_app",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío significa que le corresponde el descuento general de la app",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes",
                to="clientes.segmentoapp",
                verbose_name="Segmento de la app",
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentoapp",
            constraint=models.UniqueConstraint(
                fields=("centro_estetica", "nombre"),
                name="segmento_app_nombre_unico_por_centro",
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentoapp",
            constraint=models.UniqueConstraint(
                condition=models.Q(("es_predeterminado", True)),
                fields=("centro_estetica",),
                name="segmento_app_un_solo_predeterminado_por_centro",
            ),
        ),
        migrations.RunPython(crear_segmento_general, borrar_segmento_general),
    ]
