# Generated by Django 4.2.7 on 2026-08-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0009_segmento_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoRecuperacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_hash", models.CharField(max_length=128)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("expira_en", models.DateTimeField()),
                ("usado_en", models.DateTimeField(blank=True, null=True)),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                (
                    "usuario_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_recuperacion",
                        to="clientes.usuariocliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de recuperación",
                "verbose_name_plural": "Códigos de recuperación",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["usuario_cliente", "usado_en"],
                        name="clientes_co_usuario_e7d761_idx",
                    )
                ],
            },
        ),
    ]
