# Generated by Django 4.2.7 on 2025-11-14 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_producto",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Producto",
                "verbose_name_plural": "Categorías de Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                ("cuit", models.CharField(blank=True, max_length=13)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=300)),
                ("sitio_web", models.URLField(blank=True)),
                ("notas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proveedores",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("marca", models.CharField(blank=True, max_length=100)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("sku", models.CharField(blank=True, max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REVENTA", "Producto de Reventa"),
                            ("USO_INTERNO", "Uso Interno"),
                            ("INSUMO", "Insumo"),
                        ],
                        default="REVENTA",
                        max_length=15,
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cantidad actual en stock",
                        max_digits=10,
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nivel mínimo de stock (genera alerta)",
                        max_digits=10,
                    ),
                ),
                (
                    "stock_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nivel máximo de stock recomendado",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        default="UNIDAD",
                        help_text="Ej: UNIDAD, ML, GR, KG, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "precio_costo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de compra/costo",
                        max_digits=10,
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de venta al público",
                        max_digits=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="inventario.categoriaproducto",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="inventario.proveedor",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="empleados.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["sucursal", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (Compra)"),
                            ("SALIDA", "Salida (Venta/Uso)"),
                            ("AJUSTE", "Ajuste de Inventario"),
                            ("TRANSFERENCIA_IN", "Transferencia Entrada"),
                            ("TRANSFERENCIA_OUT", "Transferencia Salida"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_anterior",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("stock_nuevo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("notas", models.TextField(blank=True)),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_inventario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["sucursal", "stock_actual"],
                name="inventario__sucursa_8952e1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproducto",
            unique_together={("sucursal", "nombre")},
        ),
    ]
