# Generated by Django 4.2.7 on 2025-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="precio_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta unitario (para SALIDA/ventas). Si es null, usa precio_venta_final del producto",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="en_oferta",
            field=models.BooleanField(
                default=False, help_text="¿Este producto está en oferta?"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_oferta",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta durante la oferta (opcional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="costo_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo unitario (para ENTRADA/compras)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
