# Generated by Django 4.2.7 on 2025-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0002_movimientoinventario_precio_unitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
