# Generated by Django 4.2.7 on 2025-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0003_fix_codigo_barras_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio_credito",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta con tarjeta de crédito - TODO: Implementar precios por cantidad de cuotas",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_debito",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta con tarjeta de débito",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_efectivo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta en efectivo (generalmente el más bajo)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_transferencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta con transferencia bancaria",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Precio de venta al público (mantiene compatibilidad, usar precios específicos por método de pago)",
                max_digits=10,
            ),
        ),
    ]
