# Generated by Django 4.2.7 on 2026-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0004_producto_precio_credito_producto_precio_debito_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="contenido_ml",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Contenido neto en ml/gr (opcional, para estimar duración)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="duracion_estimada_dias",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Días estimados que dura una unidad con uso normal (para recompra predictiva)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="frecuencia_uso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIARIO", "Diario"),
                    ("SEMANAL", "Semanal"),
                    ("OCASIONAL", "Ocasional"),
                ],
                help_text="Frecuencia de uso típica del producto",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="pao_meses",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Period After Opening: meses de validez una vez abierto",
                null=True,
            ),
        ),
    ]
