# Generated by Django 4.2.7 on 2026-08-05 21:01

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0004_producto_precio_credito_producto_precio_debito_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Código del producto. Es la llave de cruce con Conto, así que debe ser único dentro de la sucursal",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("sku"),
                models.F("sucursal"),
                condition=models.Q(("sku", ""), _negated=True),
                name="unique_sku_per_sucursal",
            ),
        ),
    ]
