# Generated by Django 4.2.7 on 2026-08-05 22:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0005_alter_producto_sku_producto_unique_sku_per_sucursal"),
        ("inventario", "0005_producto_contenido_ml_and_more"),
    ]

    operations = []
