# Generated by Django 4.2.7 on 2026-08-08 16:56

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0006_merge_20260805_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="foto_thumb",
            field=models.ImageField(
                blank=True,
                help_text="Miniatura generada automáticamente. No cargar a mano.",
                null=True,
                storage=config.storage.storage_publico,
                upload_to="productos/thumbs/",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storage.storage_publico,
                upload_to="productos/",
            ),
        ),
    ]
