# Generated by Django 4.2.7 on 2026-08-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0007_producto_foto_thumb_alter_producto_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="beneficios",
            field=models.TextField(
                blank=True,
                help_text="Qué gana la clienta con el producto, una línea por beneficio. Se muestra en la ficha de la app.",
            ),
        ),
    ]
