# Generated by Django 4.2.7 on 2026-08-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventario", "0008_producto_beneficios"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tiendanube_product_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID del producto en Tienda Nube. Sin esto no se puede comprar desde la app: es lo que se manda al carrito",
                max_length=50,
                verbose_name="Producto en Tienda Nube",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="tiendanube_variant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID de la variante. Identifica cuál unidad, cuando el producto tiene más de una",
                max_length=50,
                verbose_name="Variante en Tienda Nube",
            ),
        ),
    ]
